name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build kh-portal Docker image
      run: docker build --tag kh-portal:ci .

    - name: Deploy kh-portal Docker Image to Firebase Hosting
      run: docker run --rm -it kh-portal:ci